//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workwiz.PaymentFramework.Shared {
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class RealEx : global::System.Configuration.ApplicationSettingsBase {
        
        private static RealEx defaultInstance = ((RealEx)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RealEx())));
        
        public static RealEx Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:2437/Realex/epage.cgi.aspx")]
        public string RealExPostUrl {
            get {
                return ((string)(this["RealExPostUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://epage.payandshop.com/epage-remote-plugins.cgi")]
        public string RealVaultRemoteUrl {
            get {
                return ((string)(this["RealVaultRemoteUrl"]));
            }
        }
    }
}
